
name: CI-FacebookLive

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/setup-node@v2
    - name: Use Node.js ${{ matrix.node-version }}

      uses: actions/setup-node@v2
      with: 
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: npm install yarn
           yarn install
           yarn build

    