
name: CI-FacebookLive

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/setup-node@v2.2.0
    - name: Use Node.js ${{ matrix.node-version }}

      uses: actions/setup-node@v2.2.0
      with: 
        node-version: ${{ matrix.node-version }}
   
    - run: npm install
           npm run build
    