
name: CI-FacebookLive

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
          npm run build
            #pm2 stop 2
            #pm2 start 2
            #pm2 save
            #sudo service nginx restart 
      #- run: npm run build --if-present
      #- run: npm test
    